### ISSUE TITLE
Implement color template based on theme color tokens

### ISSUE THREAD

**Issue by saifaldin** [m3ntorship/m3ntorship.com-v2#1]
**Story**
Color tokens are the base of all colors used in the design, where all colors in a category are a function from the main color in the category. Tokens: [Figma](https://www.figma.com/file/dZ7gP6V7YvjzLimQVrT1sa/Mentorship-DS?node-id=21%3A6661)
Please note that: color inventory has all colors that will and might be used in the desgin system, it is not meant to be implemented in the code base as a whole, only the tokens.

**Prerequisites**
- Initial project setup #2

**Tasks**
From tokens described in the design system, implement a color palette exactly similar to the tokens. Make sure that all colors in each category are a function from one main color taken from the inventory.

**Acceptance criteria**
A color palette that covers all colors in the tokens is implemented, where only the main color is taken as is, and all other colors are a function from it.

**Comment by elhaw** [comment]
The task has been added in m3ntroship-ui libirary.
https://github.com/m3ntorship/m3ntorship-ui
